use lowercase for quadbin values in SF
CartoDB/analytics-toolbox-core pull request #264
Opened 2022-07-06 07:55 UTC by volaya

2022-07-06 07:58 UTC, padawannn requested changes
It only solves the problem for quadbin, right? I've also detected the same problem for h3

2022-07-06 08:01 UTC, Jesus89 commented
For H3, let's add the functions in the h3 module
- _H3_INT_TOSTRING
- _H3_STRING_TOINT

And then use them in the tiler

2022-07-06 10:49 UTC, Jesus89 commented
Yes, but let's move the implementation of these functions to the core: https://github.com/CartoDB/analytics-toolbox-core/pull/264#issuecomment-1175911007. So we have one common unified implementation with also corresponding tests.

After merging this, update core submodule in the branch for the tiler to use the new functions

2022-07-07 14:13 UTC, volaya commented
@Jesus89 The PR already includes the H3 functions and corresponding tests. Let me know when you can review it, so it can be merged and I can update the AT repo (I have that PR already finished, waiting for this to be merged)

2022-07-07 15:44 UTC, Jesus89 approved these changes
LGTM

Suggested an optimization for H3_INT_TOSTRING

Complete these pending updates before merging:
- Update common/bigquery/version
- Update modules/h3/bigquery/CHANGELOG.md
- Update modules/h3/bigquery/package.json
- Update common/snowflake/version
- Update modules/h3/snowflake/CHANGELOG.md
- Update modules/h3/snowflake/package.json

2022-07-07 15:44 UTC, Jesus89 commented on modules/h3/bigquery/sql/H3_INT_TOSTRING.sql
> +  LOWER(FORMAT('%X', h3))
You can rewrite this as `FORMAT('%x', h3)`

2022-07-08 05:24 UTC, merged