Feature/sc 246044/migrate at core databricks modules
CartoDB/analytics-toolbox-core pull request #288
Opened 2022-08-17 08:15 UTC by aarroyosal

shortcut tickets:
- https://app.shortcut.com/cartoteam/story/246038/add-at-databricks-scaffolding
- https://app.shortcut.com/cartoteam/story/246044/migrate-at-core-databricks-modules

Acceptance:

Install the libraries needed for the databricks AT (README)
[Setup databricks databricks CLI authentication (via token)](https://docs.databricks.com/dev-tools/cli/index.html#set-up-authentication)
test the make commands
make build|clean|lint|deploy CLOUD=databricks
test the deployed functions in a databricks notebook `select carto_dev_data.st_x(geom) as latitude from...`

2022-08-17 08:17 UTC, Jesus89 commented on clouds/databricks/common/Makefile
> +	sed -i '.bkp' '1s/^/USE ${DB_SCHEMA};\n/' $(SQL_PATH)
To make this work in GNU/Linux must be `sed -i'.bkp'` (without the space)

2022-08-19 12:03 UTC, Jesus89 requested changes
Awesome job!

I left some in-line comments. I would remove the entire cloud/databricks/.github section for now. In general for the docs, we should review the style of the examples to follow the convention:
- Uppercase syntax: SELECT, AS, etc
- Ending with ;

NOTE: we leave the automatic generation of createUDFs to the next PR.

2022-08-22 09:36 UTC, aarroyosal commented on clouds/databricks/.github/release-drafter.yml
> +name-template: '$NEXT_MINOR_VERSION'
Done

2022-08-22 09:37 UTC, aarroyosal commented on clouds/databricks/README.md
> +# CARTO Analytics Toolbox
I have removed the badges and updated the links. I have read the rest and looks good to me

2022-08-22 09:41 UTC, aarroyosal commented on clouds/databricks/common/requirements.txt
> +attrs==22.1.0
Yeah, they are dependencies of dependencies, that's how pip freeze works. I have already cleaned them

2022-08-22 09:41 UTC, aarroyosal commented on clouds/databricks/libraries/scala/LICENSE
> +Copyright (c) 2021, CARTO
Changed

2022-08-22 09:41 UTC, aarroyosal commented on clouds/databricks/modules/accessors/doc/ST_COORDDIM.md
> +SELECT carto.ST_COORDDIM(ST_MAKEPOINTM(1, 2, 3));;
Done

2022-08-22 09:42 UTC, aarroyosal commented on clouds/databricks/modules/accessors/doc/ST_DIMENSION.md
> +SELECT ST_DIMENSION(ST_GEOMFROMWKT("LINESTRING(0 0, 1 1)"))
Done

2022-08-22 09:42 UTC, aarroyosal commented on clouds/databricks/modules/predicates/doc/ST_CROSSES.md
> +  select ST_GEOMFROMWKT("LINESTRING (1 0, 1 2)") as lineA,
Changed

2022-08-22 09:43 UTC, aarroyosal commented on clouds/databricks/libraries/scala/core/src/main/scala/com/carto/analyticstoolbox/index/ST_ExtentFromGeom.scala
> +  def function = _.extent
Fixed

2022-08-22 10:57 UTC, Jesus89 approved these changes
LGTM

2022-08-22 11:07 UTC, merged