adapted docs to new documentation
CartoDB/analytics-toolbox-core pull request #380
Opened 2023-01-20 09:19 UTC by volaya

# Description

This PR adapts the documentation to the new gitbook approach

2023-01-23 14:51 UTC, Jesus89 requested changes
Great job!

Everything looks good. The only thing to revert is the changes applied in the CHANGELOG files. Please, update/revert those changes and we are ready to merge

2023-01-23 15:01 UTC, Jesus89 commented
Note that logos were lost with the documentation platform change, so I have fixed that in the README.

2023-01-24 07:57 UTC, volaya commented
Should be fixed now.

2023-01-24 11:45 UTC, Jesus89 approved these changes

2023-01-24 11:45 UTC, merged